steps:
  # 0. Get previous build for cache
  - name: golang:1.19
    entrypoint: /bin/bash
    args:
      - -c
      - go build -o bdjuno ./cmd/bdjuno/main.go
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      "compute",
      "ssh",
      "--project",
      "$PROJECT_ID",
      "--zone",
      "us-central1-a",
      "builder@${_INSTANCE_NAME}",
      "--command",
      "systemctl stop bdjuno && sleep 5 && systemctl start bdjuno"
    ]
artifacts:
  objects:
    location: 'gs://${_GCP_BUCKET}/'
    paths: ['bdjuno']
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' # 8 cores
  dynamic_substitutions: true

