steps:
  # 0. Setup GitHub SSH key and configuration
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['GITHUB_SSH_KEY']
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "$$GITHUB_SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
    volumes:
      - name: 'ssh'
        path: /root/.ssh

  # 1. Build the app
  - name: golang:1.19
    entrypoint: /bin/bash
    args:
      - -c
      - |
        ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
        git config --global url."git@github.com:".insteadOf "https://github.com/" 
        chmod 0600 /root/.ssh/id_rsa
        go env -w GOPRIVATE=github.com/villagelabsco/*
        go build -o bdjuno ./cmd/bdjuno/main.go
    volumes:
      - name: 'ssh'
        path: /root/.ssh

#  # 2. Restart the BDJuno systemd service
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: [
#      "compute",
#      "ssh",
#      "--project",
#      "$PROJECT_ID",
#      "--zone",
#      "us-central1-a",
#      "builder@${_INSTANCE_NAME}",
#      "--command",
#      "sudo systemctl restart bdjuno"
#    ]

artifacts:
  objects:
    location: 'gs://${_GCP_BUCKET}/'
    paths: [ 'bdjuno' ]
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' # 8 cores
  dynamic_substitutions: true
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/VILLAGE_REPO_DEPLOYER_SSH_KEY/versions/latest
      env: 'GITHUB_SSH_KEY'

